---
# tasks file for testing that variables of ansible-role jonaspammer.pip are set correctly

- name: test if pip_state is set correctly
  ansible.builtin.assert:
    that:
      - pip_state is defined
      - pip_state in ["forcereinstall", "latest", "present"]
    quiet: true
