---
# tasks file of ansible-role jonaspammer.pip

- name: Install pip from system packages.
  ansible.builtin.package:
    name: "{{ [pip_package] }}"
    state: present

- name: Install pip using pip to ensure desired version.
  ansible.builtin.pip:
    name: "pip"
    version: "{{ pip_version }}"
    executable: "{{ pip_executable }}"

- name: Install defined pip packages.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  loop: "{{ pip_install_packages }}"
