---
# tasks file of ansible-role jonaspammer.pip

- name: Install pip system packages.
  ansible.builtin.package:
    name: "{{ pip_package }}"
    state: present

- name: import tasks to determine default pip version
  ansible.builtin.import_tasks: determine-default-pip-version.yml

- name: Install pip using pip to ensure desired version.
  ansible.builtin.pip:
    name: "pip"
    state: latest
    version: "{{ pip_version }}"
    executable: "{{ pip_executable }}"

- name: Install virtualenv system packages.
  package:
    name: "{{ pip_virtualenv_packages }}"
    state: present
  when: (pip_install_packages_virtualenv is defined
    or pip_install_packages | map(attribute='virtualenv') | select('defined') | list | length > 0)

- name: Install defined pip packages.
  pip:
    requirements: "{{ item.requirements | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    umask: "{{ item.umask | default(pip_install_packages_umask | default(omit)) }}"
    executable: "{{ pip_executable if item.virtualenv is not defined and pip_install_packages_virtualenv is not defined else omit }}"
    virtualenv: "{{ item.virtualenv | default(pip_install_packages_virtualenv | default(omit)) }}"
    virtualenv_command: "{{ item.virtualenv_command | default(pip_install_packages_virtualenv_command | default(omit)) }}"
    virtualenv_python: "{{ item.virtualenv_python | default(pip_install_packages_virtualenv_python | default(omit)) }}"
    virtualenv_site_packages: "{{ item.virtualenv_site_packages | default(pip_install_packages_virtualenv_site_packages | default(omit)) }}"
    extra_args: "{{ item.extra_args | default(pip_install_packages_extra_args | default(omit)) }}"
  environment: "{{ item.environment | default(pip_install_packages_environment | default(omit)) }}"
  loop: "{{ pip_install_packages }}"
