---
# tasks file of ansible-role jonaspammer.pip

- name: Install pip from system packages.
  ansible.builtin.package:
    name: "{{ [pip_package] }}"
    state: present

- name: Install pip using pip to ensure desired version.
  ansible.builtin.pip:
    name: "pip{{ pip_version }}"
    executable: "{{ pip_executable }}"