---
- name: Converge
  hosts: all

  roles:
    - name: "ansible-role-pip"

  vars:
    pip_install_packages:
      - role: pre-commit
        version: "1.0.0"
      - role: awscli
      - role: ipaddress
        virtualenv: /virtualenv
