---
- name: Converge
  hosts: all

  roles:
    - role: "ansible-role-pip"

  vars:
    pip_install_packages:
      - name: pre-commit
        version: "1.0.0"
      - awscli
      - name: ipaddress
        virtualenv: /virtualenv
