---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update Debians' APT cache.
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: "ansible-role-pip"

  vars:
    pip_install_packages:
      - name: awscli
        version: "1.22.97"
      - awscli
