---
- name: output some generally helpful debug information about the provisioned machine
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - ansible.builtin.include_tasks: ../resources/debug.yml

### Actual Role Verification Tasks:
- name: Verify
  hosts: all

  tasks:
    - name: stat /virtualenv
      ansible.builtin.stat:
        path: /virtualenv
      register: pip__register_stat_virtualenv

    - name: Test if /virtualenv exists and is a directory.
      ansible.builtin.assert:
        that:
          - pip__register_stat_virtualenv.stat.exists
          - pip__register_stat_virtualenv.stat.isdir

    - name: execute pip freeze
      ansible.builtin.shell: "pip freeze"
      register: pip__register_shell_pip_freeze

    - name: Test if defined package was installed.
      ansible.builtin.assert:
        that:
          - '"awscli" in pip__register_shell_pip_freeze.stdout'
    - name: Test if defined package was installed in correct version.
      ansible.builtin.assert:
        that:
          - '"awscli==1.22.97" in pip__register_shell_pip_freeze.stdout'
