---
- name: output some generally helpful debug information about the provisioned machine
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - ansible.builtin.include_tasks: debug.yml

### Actual Role Verification Tasks:
- name: Verify
  hosts: all

  # TODO insert actual verify tasks
